---
#################
## Run Checkov ##
#################

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

name: Checkov
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

##########################
# Prevent duplicate jobs #
##########################
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read # for actions/checkout to fetch code
  security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
  actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status

###############
# Run the job #
###############
jobs:
  ###########
  # Checkov #
  ###########
  checkov:
    name: Checkov
    runs-on: ubuntu-latest
    steps:
      ############################
      # Checkout the source code #
      ############################
      - name: Checkout Code
        uses: actions/checkout@v3.1.0

      #####################
      # Run Checkov #
      #####################
      - name: Checkov GitHub Action
        uses: bridgecrewio/checkov-action@v12
        with:
          output_format: cli,sarif
          output_file_path: console,results.sarif

      #####################
      # Upload SARIF file #
      #####################
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        if: success() || failure()
        with:
          sarif_file: results.sarif
