---
#################
## Sync labels ##
#################

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

name: Sync labels
on:
  workflow_dispatch:

##########################
# Prevent duplicate jobs #
##########################
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

###############
# Run the job #
###############
jobs:
  ###############
  # Sync labels #
  ###############
  tf-fmt:
    name: Sync labels
    runs-on: ubuntu-latest
    steps:
      ##################################
      # Sync labels with template Repo #
      ##################################
      - name: Sync labels
        uses: EndBug/label-sync@v2.3.1
        with:
          config-file: 'https://raw.githubusercontent.com/geekcell/template-terraform-module/main/.github/labels.json'
